In [1]:
# Загружаем библиотеки:
# для работы с математикой
import numpy as np

In [2]:
# Фиксируем начальное условие для генератора случайных чисел
np.random.seed(42)

In [3]:
# Создайте случайную матрицу А1 размерностью 5 на 5
A1 = np.random.randint(0, 9, size = (5, 5))
print(f'A1 =\n{A1}')
# Определитель, ранг и собственные значения
print(f'det A1 = {np.linalg.det(A1)}')
print(f'rang A1 = {np.linalg.matrix_rank(A1)}')
print(f'Собственные значения: {np.linalg.eigvals(A1)}\nСобственные значения λ4 и λ5 комплексные')

A1 =
[[6 3 7 4 6]
 [2 6 7 4 3]
 [7 7 2 5 4]
 [1 7 5 1 4]
 [0 5 8 0 2]]
det A1 = -2580.0000000000005
rang A1 = 5
Собственные значения: [21.63088392+0.j         3.42889044+0.j        -4.47836617+0.j
 -1.7907041 +2.1355836j -1.7907041 -2.1355836j]
Собственные значения λ4 и λ5 комплексные


In [4]:
# Транспонируйте матрицу A1
A1_T = np.transpose(A1)
print(f'A1_T =\n{A1}')
# Определитель, ранг и собственные значения
print(f'det A1_T = {np.linalg.det(A1_T)}\nОпределители транспонированной и исходной матриц равны')
print(f'rang A1_T = {np.linalg.matrix_rank(A1_T)}\nРанги транспонированной и исходной матриц равны')
print(f'Собственные значения: {np.linalg.eigvals(A1_T)}\nСобственные значения транспонированной и исходной матриц равны, но в данном случае часть из них переставлены местами')

A1_T =
[[6 3 7 4 6]
 [2 6 7 4 3]
 [7 7 2 5 4]
 [1 7 5 1 4]
 [0 5 8 0 2]]
det A1_T = -2580.0000000000005
Определители транспонированной и исходной матриц равны
rang A1_T = 5
Ранги транспонированной и исходной матриц равны
Собственные значения: [21.63088392+0.j         3.42889044+0.j        -1.7907041 +2.1355836j
 -1.7907041 -2.1355836j -4.47836617+0.j       ]
Собственные значения транспонированной и исходной матриц равны, но в данном случае часть из них переставлены местами


In [5]:
# Найдите обратную матрицу для А1
A1_inv = np.linalg.inv(A1)
print(f'A1_inv =\n{A1_inv}')
# Определитель, ранг и собственные значения
print(f'det A1_inv = {np.linalg.det(A1_inv)}\nОпределитель обратной матрицы равен определителю исходной матрицы в степени -1: 1 / det A1 = {np.linalg.det(A1) ** -1}')
print(f'rang A1_inv = {np.linalg.matrix_rank(A1_inv)}')
print(f'Собственные значения: {np.linalg.eigvals(A1_inv)}')
print(f'Произведение исходной и обратной матриц даёт единичную матрицу:\nA1*A1_inv =\n{np.dot(A1, A1_inv)}')

A1_inv =
[[ 0.02906977 -0.25116279  0.21976744 -0.21046512  0.27093023]
 [-0.12403101 -0.02170543  0.10232558  0.07131783  0.05736434]
 [ 0.03488372  0.01860465 -0.01627907 -0.13255814  0.16511628]
 [-0.01744186  0.39069767 -0.09186047 -0.03372093 -0.28255814]
 [ 0.17054264 -0.02015504 -0.19069767  0.35193798 -0.30387597]]
det A1_inv = -0.00038759689922480614
Определитель обратной матрицы равен определителю исходной матрицы в степени -1: 1 / det A1 = -0.00038759689922480614
rang A1_inv = 5
Собственные значения: [ 0.29163953+0.j         -0.23054282+0.27494406j -0.23054282-0.27494406j
 -0.22329572+0.j          0.0462302 +0.j        ]
Произведение исходной и обратной матриц даёт единичную матрицу:
A1*A1_inv =
[[ 1.00000000e+00  4.16333634e-17  0.00000000e+00 -1.11022302e-16
   4.44089210e-16]
 [-2.77555756e-17  1.00000000e+00  0.00000000e+00  1.66533454e-16
  -1.11022302e-16]
 [ 0.00000000e+00  8.32667268e-17  1.00000000e+00  2.22044605e-16
   0.00000000e+00]
 [-1.11022302e-16  2.77555756

In [6]:
# Создайте диагональную матрицу - поэлементно перемножив единичную
# матрицу I и случайную матрицу A2 размерности 4 на 4
I = np.eye(4)
print(f'I =\n{I}')
A2 = np.random.randint(0, 9, size = (4, 4))
print(f'A2 =\n{A2}')
print(f'I*A2 =\n{I*A2}')
# Определитель, ранг и собственные значения
print(f'det I*A2 = {np.linalg.det(I*A2)}')
print(f'rang I*A2 = {np.linalg.matrix_rank(I*A2)}')
print(f'Собственные значения: {np.linalg.eigvals(I*A2)}')

I =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
A2 =
[[6 3 8 2]
 [4 2 6 4]
 [8 6 1 3]
 [8 1 8 4]]
I*A2 =
[[6. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 4.]]
det I*A2 = 47.999999999999986
rang I*A2 = 4
Собственные значения: [6. 2. 1. 4.]


In [13]:
# Создайте нулевую матрицу размерности 3 на 3
Z = np.zeros((3, 3))
print(f'Z =\n{Z}')
# Определитель, ранг и собственные значения
print(f'det Z = {np.linalg.det(Z)}')
print(f'rang Z = {np.linalg.matrix_rank(Z)}')
print(f'Собственные значения: {np.linalg.eigvals(Z)}')
print('Определитель, ранг и собственные значения равны нулю!')

Z =
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
det Z = 0.0
rang Z = 0
Собственные значения: [0. 0. 0.]
Определитель, ранг и собственные значения равны нулю!
